settings:
  legacy:
    force: false
    interval: 1s
server:
  status: true
  open: true
  port: 9090
  host: localhost
schema:
- name: goask
  path: cmd/goask-server/
  commands:
    install:
      status: true
    run:
      status: true
    fmt:
      status: true
      args:
        - -s
        - -w
  args:
    - -mod=vendor
  watcher:
    paths:
    - ../../
    extensions:
    - go
    - html
    - tmpl
    ignored_paths:
    - ../../.git
    - ../../.realize
    - ../../vendor
    - ../../web
