settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: goask
  path: ./cmd/goask-server
  commands:
    run:
      status: true
      args:
      - -mod=vendor
  watcher:
    extensions:
    - go
    paths:
    - ../../
    ignore:
      paths:
      - ../../.git
      - ../../.realize
      - ../../vendor
      - ../../web
