language: go

sudo: false

go:
  - 1.11.x
  - 1.12.x
  - tip

go_import_path: github.com/Alireza-Ta/goask

services:
  - postgresql

before_script:
  - psql -c 'create database "GoaskTest";' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'secret;'" -U postgres
  - psql -c '\l' -U postgres

addons:
  - postgresql: "9.6"

env:
  - GO111MODULE=on

script:
  - ./.travis.gofmt.sh
  - go test -v -race $(go list ./... | grep -v vendor)
